### PR TITLE
Fix dnf install

### PR DESCRIPTION
**Pull request by ArvindNair001**

### CODE REVIEW

**Comment by bddenhartog** [comment]
Thanks! 

Did you run into an issue with the position of the `-y` parameter? This is actually completely valid in all of the versions of Fedora that we support, and while it is not my preferred code style, I don't see a reason to have a PR for such a minor formatting adjustment. It would make sense to include this in something along the lines of a repository-wide clean-up task.

**Comment by ArvindNair001** [comment]
Yes I've tested your original code, as it is the only reason I've reached this repo because it had been aborting the install for some odd reason. I've never tried passing -y parameter before install but i think logically it makes sense for -y to be added after "dnf install" anyways the code worked for me after correction. I'm on fedora 26 btw !! and i love fedy  its a great initiative

**Comment by bddenhartog** [comment]
Thanks for the kind words! I'm glad you find Fedy useful :)

> I've never tried passing -y parameter before install but i think logically it makes sense for -y to be added after "dnf install" anyways the code worked for me after correction

While the script may have worked for you after you made a change, the change in this pull request was not the reason for the failure. Passing the options before arguments is actually the correct format, as you can see from `man dnf`:

```
DNF(8)

NAME
       dnf - DNF Command Reference

SYNOPSIS
       dnf [options] <command> [<args>...]
```

**Comment by bddenhartog** [comment]
P.S., I'd be more than happy to work with you to figure out what your issue was -- although I'm inclined to think it was probably just network-related.

**Pull request closed without merging**
