### PR TITLE
Added HandBrake

### PR DESCRIPTION
**Pull request by Rohan62442**
Added HandBrake-gui and Handbrake-cli, using negativo17 handbrake repository. See #179

### CODE REVIEW

**Comment by satya164** [comment]
Uninstalling should also delete the repo.

Thanks :)

**Comment by Rohan62442** [comment]
The Handbrake repo also contains other software like libdvdcss and makemkv. Removing the repo on handbrake's uninstall may cause problems for those people who are using them.

**Comment by satya164** [comment]
libdvdcss is already in the ozon repo. May be detect if the user is using those software and remove the repo if not?

**Comment by Rohan62442** [comment]
Well, it's in this repo as well. So it might give a false positive. Any suggestions?

**Comment by satya164** [comment]
Hey, can you fix the merge conflicts?

**Pull request closed without merging**
