### PR TITLE
Integrate developer plugins, restructure plugin categories

### LINKED ISSUE #397: Better separation of concerns for categories and applications
## Overview

I started using Fedy shortly after moving to Fedora over a year ago. It wasn't until a few weeks ago that I discovered [folkswithhats/fedy-plugins-developers](https://github.com/folkswithhats/fedy-plugins-developers). I'm opening this issue to gain clarity as to why the two are maintained separately, and propose a solution for absolving the need to do so. The immediate issues I see with keeping certain plugins separate from the main app repo are listed below:
- **Inaccessibility**. I can't remember exactly how I stumbled upon it, but the developer plugins repository is not made visible... anywhere, as far as I can tell.
- **Duplication**. This causes unecessary maintenance overhead. There are several plugins which exist in both repositories:
  - Atom
  - Brackets
  - Oracle JDK
  - Sublime text (although the _developers_ repo contains v2, and _this_ repo contains v3)
  - Visual Studio Code
## Proposed solution

I think using additional categories is the right solution here:
- Apps (contains standard applications, like browsers, music players, games, etc)
- Developer Apps (contains IDEs, editors, SDKs, etc - things specific to developers)
- Utilities (contains things like system libraries, e.g. `libdvdcss`, multimedia codecs, fonts, etc)
- Themes (no change in category meaning)
- Tweaks (no change in category meaning)

This will allow for easy integration of the existing `fedy-plugins-developers` plugins, and will help separate some of the overlapping categories with the current layout.

I am, of course, happy to do this myself and submit a PR -- I just wanted to see if this is something that would be beneficial/appreciated before I got started.

### PR DESCRIPTION
**Pull request by bddenhartog**
This patch:

- Integrates the plugins and history from the `fedy-plugins-developers` repository, which can (upon PR acceptance) be empty/deprecated and users redirected to fedy core. The history from the integrated repository has been modified to alter paths to the plugin files, moving them into the `plugins/` directory to match the structure of the core project (this repository). This does not create a _perfect_ history, unfortunately, as it appears the `fedy-plugins-developers` repository history was originally yanked/forked from core, with several files removed (but not as part of a commit). I'm not sure if this is something we really care about.

- Adds two new plugin categories: `Editors and IDEs` and `Utilities`. The latter is intended to hold plugins like system utilities or development libraries, such as AV codecs or SDKs. The eventual goal here is to keep the `Apps` categories clear of things that aren't GUI applications, and to add better category lists so it is easier for users to find what they want to install.

- Refactors the Eclipse Automotive plugin to shorten the name displayed in the Fedy application. Previously, this name extended beyond the default width for the Fedy application, causing a poorer user experience.

- Refactors the icon names for the Sublime Text plugins to explicitly specify the versions (2 & 3)

**IMPORTANT**
Upon merging, please add `Closes #397` to the bottom of the commit message, so that the related issue is closed. It is important that a **non-ff** merge is performed. **Do not** perform a squash merge. Since the Github UI prevents a non-ff merge (because it is not enabled for this repository), this merge should be performed from the command line:

```text
# Go the the repository on your system
cd /path/to/the/fedy/repo

# Update remote refs and the master branch
git checkout master && git pull

# Merge this feature branch
# Make sure you add "Closes #397" under the automatically-generated message!
git merge --no-ff feature/397/integrate-developer-plugins

# Push up to the remote
git push
```

Relates to #397

### CODE REVIEW

**Comment by bddenhartog** [comment]
@Abhinav1217 @satya164 @bheru27 I'd appreciate a once-over from you guys to make sure everything fits with what we want to do. If you spot any issues, let me know. I can handle merging it into `master` when it's complete.

**Comment by Abhinav1217** [comment]
Even though I am partial towards keeping plugins and app in separate repos. We didn't properly convey the purpose of the two repos to the community, and this has caused confusion.
   
Everything looks ok here so I think we can merge this pull. With a clean slate, we can properly pave the path for future.

Maybe after this, we can remove few old plugins which were not needed for a long time but we kept in the repo for legacy compatibility sake.

**Comment by Abhinav1217** [comment]
I have tested this merge on only one VM with default fedora gnome.  If you want I can make some time to test it in other editions too.

**Comment by bddenhartog** [comment]
@Abhinav1217 I don't really see the need for extensive testing; this patch isn't altering any existing plugins in either repository (at least in any way that affects (un)installation). I'm working on building out logical unit tests for us, which can be executed in a docker container and automated on Travis-CI. It's a bit tricky due to the variety in each plugin but I'm making progress. I'll write up an issue tomorrow.

I think we could definitely have a discussion around the codebase organization, if you'd like to. I also agree that a good next step after this is merged (I'll take care of this in a few hours) is doing some pruning. Do you want to make an issue for this?

Also, the developer plugins repository should be cleared out and a README added directing users here. I'll migrate issues and make the appropriate changes in a PR, but I don't have write access at the moment so someone else will have to merge it.

**Comment by satya164** [comment]
> but I don't have write access at the moment

You should have now

**Comment by bddenhartog** [comment]
Thanks @satya164.

**Pull request merged**
