### PR TITLE
Recategorize development tools

### PR DESCRIPTION
**Pull request by danstewart**

### CODE REVIEW

**Comment by bddenhartog** [comment]
I'm okay with this, but the initial goal with the final category name was to allow us to more accurately categorize our plugins, with the future goal of reworking the UI to account for any number of tabs (or better yet, refactor the tabs into a dropdown-esque or searchable field).

This would allow us to extend the included plugins to a much larger quantity, while still keeping a sane UI that can be easily navigated.

**Comment by danstewart** [comment]
@bddenhartog All of them apart from 2 (GitKraken & Arduino) are editors or IDEs.
Might make more sense to split them up again when there are more plugins 😄

**Comment by bddenhartog** [comment]
Fair point 👍

**Comment by danstewart** [comment]
That being said - I just noticed SmartGit and Gnome Development Tools are both under Utilities - maybe GitKraken and Arduino would be better there? The lines between categories are a little fuzzy.
I think it would be preferrable to have all development related stuff away from non development stuff.

**Comment by bddenhartog** [comment]
> The lines between categories are a little fuzzy.

Agreed. I intend to revisit every plugin and provide saner categorization in the future. "Utilities" was provided by #416, and you're right, GitKraken should have been included in there initially. "Arduino" is actually [an IDE](https://www.arduino.cc/en/Main/Software), so it belongs under "Development Tools" in this PR.

**Comment by bddenhartog** [comment]
@danstewart There's more (slightly outdated) info on the initial issue I logged for integrating the dev plugins: #397

**Comment by danstewart** [comment]
@bddenhartog Done.

**Comment by danstewart** [comment]
@bddenhartog Done - tried squashing my commits and somehow missed one but rolled back to your commit renaming visual studio code - no idea how I managed that.

Should Gnome Dev Tools stay where it is?

**Comment by bddenhartog** [comment]
Whoops - I was adding instructions for you to fix your branch that had diverged from `folkswithhats/fedy/master` due to your change on VSC, but I see that you're fixing it another way :)

**Pull request closed without merging**
