### PR TITLE
Fixed libdvdcss install

### PR DESCRIPTION
**Pull request by DStewart1997**
Fixed the libdvdcss installer. Solves #272. Using [RPMFind](http://rpmfind.net/linux/rpm2html/search.php?query=libdvdcss&submit=Search%20...).

### CODE REVIEW

**Comment by Abhinav1217** [comment]
Originally it was provided by Ozon repository.   
@satya164 Can we merge this?

**Comment by satya164** [comment]
@Abhinav1217 I think we should use the negativo repo.

**Comment by Abhinav1217** [comment]
Agreed, I have used it too. It is better and more stable. 
Provides more software also, including handbreak and spotify #277 . 

@DStewart1997 Can you send PR replacing RPMFind with NegativeIO .

**Comment by DStewart1997** [comment]
@Abhinav1217 Yeah, no problem. Are you two wanting Spotify added back into the plugins or should I make one for the "Community Repos" as discussed in in #260?

I have already made a Chromium community plugin [here](https://github.com/DStewart1997/fedy-plugins-community).

**Comment by satya164** [comment]
@Abhinav1217 May be create community plugin repo and give people access?

**Comment by paltas** [comment]
@Abhinav1217 Sounds like a good idea, i will for sure contribute to it.

**Pull request closed without merging**
