### PR TITLE
[WIP] Expand Software Offering: Pixeluvo

### PR DESCRIPTION
**Pull request by 89luca89**
Add Pixeluvo Application

This PR is part of a rework on another PR
I splitted in many little PR as requested

### CODE REVIEW

**Comment by Abhinav1217** [comment]
Do we need this when there are multiple free and open source ( even free to use apps ) in this category? Does this offer something really unique over them.

**Comment by 89luca89** [comment]
Just found it very intuitive and nice UI
Feel free to judge by yourself if including it or not

**Comment by bddenhartog** [comment]
> Do we need this when there are multiple free and open source ( even free to use apps ) in this category? Does this offer something really unique over them.

Why would we want to limit the choices users have?

**Comment by Abhinav1217** [comment]
There is no free to use version for this app. Feature list and UI does not provide anything unique compared alternatives like darktable. The trial version is also a limited feature trial. It is limited to 800x600px images only.

**Comment by bddenhartog** [comment]
Statements that should _probably_ be considered when thinking about whether or not an application should make it into Fedy:

> * There is no free to use version for this app.
> * The trial version is also a limited feature trial. It is limited to 800x600px images only.

These statements lead to a pretty poor end user experience after installation. Of course, this stems from an assumption that users are not researching the application before clicking 'install', and thus the limited feature trial, and lack of of free version, will probably come as a surprise.

Statements that should _not_ be a factor in whether or not an application makes it into Fedy:

> * Feature list and UI does not provide anything unique compared alternatives

All I'm getting at is that applications are never _exactly_ the same, and we shouldn't reject an application for being similar to another - that prevents our users from feeling out the alternatives and finding what works for them.

That said, closing due to the aforementioned reasons.

**Pull request closed without merging**
