### PR TITLE
Add support for Moka icon theme

### PR DESCRIPTION
**Pull request by stephenfin**

### CODE REVIEW

**Comment by satya164** [comment]
Is Moka actively maintained now a days? Last time I spoke to sam, he told me that it's not.

**Comment by stephenfin** [comment]
> Is Moka actively maintained now a days? Last time I spoke to sam, he told me that it's not.

There are repos published for Fedora 24, so I would assume so?

**Comment by bddenhartog** [comment]
I've reached out to @snwh to get a status update so that a decision can be made about this PR.

**Comment by bddenhartog** [comment]
@stephenfin unfortunately, this is being closed due to the infrequency with which the moka icon repository is maintained. Including projects that are likely to not work with a future version simply causes issues in the future. You can add this plugin locally by adding the `mokaicontheme.plugin` directory to `~/.local/share/fedy`.

**Pull request closed without merging**
