### PR TITLE
PhpStorm Plugin

### PR DESCRIPTION
**Pull request by Squarius**
Jetbrains PhpStorm

### CODE REVIEW

**Comment by DStewart1997** [comment]
Hi, the developers plugins are found in the "fedy-developer-plugins" repo and PHPStorm is already [there](https://github.com/folkswithhats/fedy-plugins-developers).

**Comment by Squarius** [comment]
Oh. Okay Thanks. But how can i use these Installers in Fedy installed from your Repo? For example PhpStorm was in fedy before.

**Comment by DStewart1997** [comment]
It isn't my repo but you have to download the zip of the developer plugins, unzip it and move all of the *.plugin directories to /usr/share/fedy/plugins/. Restart fedy and they'll be there.

Was speaking to @satya164 about adding an easier way to add the developer plugins but nothing has come of it yet. I am looking into it to see if I could add the functionality.

**Comment by Squarius** [comment]
Okay nice. Thank you for the info.

**Comment by satya164** [comment]
@DStewart1997 You can place plugins under ~/.local/share/fedy/plugins without needing root. Feel free to take up the task. I don't have enough time to actively work on this. You can discuss this with @Rohan62442 and @Abhinav1217 . We have a Telegram group if you wanna talk there.

**Comment by DStewart1997** [comment]
@satya164 I'm currently looking through the Gnome JS tutorials on gnome.org to try and familiarise myself with it but yeah I'm interested in trying to add this in if neither @Rohan62442 or @Abhinav1217 feel like taking it upon themselves.

**Comment by Abhinav1217** [comment]
@DStewart1997 I have started working on a website to submit community plugins, Conceptually similar to PackageControl.io . I have kept  scope to add an api which can be used by fedy application to download and install plugins by itself. But haven't started working on that part yet.  I am happy to discuss ideas with you.

**Comment by DStewart1997** [comment]
@Abhinav1217 Yeah, it sounds really interesting. I'm happy to help in any way I can, I use Telegram so we can talk on there if you want like @satya164 suggested.

**Pull request closed without merging**
