### PR TITLE
Added Mumble

### PR DESCRIPTION
**Pull request by PhnxRbrn**
Added Mumble from copr.  Fedora 22 from jamielennox and Fedora 21 from lkiesow.

### CODE REVIEW

**Comment by satya164** [comment]
If it's only for 64-bit, you should hide the plugin under 32-bit. See here - https://github.com/folkswithhats/fedy/blob/master/plugins/grub2.plugin/metadata.json#L10

**Comment by PhnxRbrn** [comment]
I understand I need to add the show line but how do I specify that it only shows for 64bit

**Comment by satya164** [comment]
@PhnxRbrn Something like following should work,

"show": { "command": " test $(uname -m) = x86_64" }

**Comment by PhnxRbrn** [comment]
OK I will update both mumble and obs-studio to fox this

**Comment by PhnxRbrn** [comment]
Updated

**Comment by Rohan62442** [comment]
@PhnxRbrn Could you rework this using lkiesow's [Copr] (https://copr.fedoraproject.org/coprs/lkiesow/mumble/) repo and submit it again? I believe it includes all Fedora versions now..

**Pull request closed without merging**
