### PR TITLE
Add: Popcorn-Time.sh

### PR DESCRIPTION
**Pull request by cadesalaberry**
Any comment is welcome!

Cheers

### CODE REVIEW

**Comment by bddenhartog** [comment]
@Abhinav1217, doesn't this PR leave the downloaded file on the user's filesystem? Just gave it a quick scan but perhaps this was merged in hastily.

**Comment by satya164** [comment]
@bddenhartog All plugins do that. This allows to carry them over to a new machine if needed. Probably a new plugin to clear Fedy's cache will be useful.

**Comment by bddenhartog** [comment]
@satya164 This particular installation script isn't using any kind of cache directory, though, it's simply downloading to the user's current directory. If I'm in `/var/log/whatever`, it downloads and leaves the compressed file there. If I'm in `/home/user/mydir`, it downloads and leaves it there.

**Comment by satya164** [comment]
it cd's to cache directory before the download - https://github.com/folkswithhats/fedy/pull/413/files#diff-3602ef5bf528974e5f9931d8b69876a9R12

**Comment by bddenhartog** [comment]
Wow, I have no idea how I missed that. Must need to change my contacts. Whoops!

**Comment by satya164** [comment]
xD

**Pull request merged**
