### PR TITLE
Added Spacemacs plugin

### PR DESCRIPTION
**Pull request by footvaalvica**
NOTE: This only works if you already have Emacs installed

### CODE REVIEW

**Comment by antmak** [comment]
"label": "Revert",
			"command": "run-as-root -s **REVERT**.sh"

**Comment by footvaalvica** [comment]
Thanks for spotting that. Fixed.

**Comment by Abhinav1217** [comment]
I have been using for nearly half a month, It is good editor. It is better suited if you would post the PR to https://github.com/folkswithhats/fedy-plugins-developers . It is where we currently keep all the plugins, separated from fedy app. I would merge PR on that repo. 

I think it would be better if you could add `dnf -y install emacs` on the script itself.  A plugin to install software should install its dependencies as well.  That said, is there is a copr repo for this, it would be great, since it would be easier to manage all its dependencies as  well.

**Comment by footvaalvica** [comment]
I have made a PR on https://github.com/folkswithhats/fedy-plugins-developers. Closing this one.

**Pull request closed without merging**
